name: Sync Content
on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Sync content
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_DOC_ID: ${{ secrets.GOOGLE_DOC_ID }}
        run: node scripts/sync-content.mjs
        
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/content/homepage.json
          git commit -m "Update content from Google Docs" || exit 0
          git push